name: Experiment
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/experiment.yml
jobs:
  env:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-26, macos-latest, windows-latest, ubuntu-slim]
    runs-on: ${{ matrix.runner }}
    permissions:
      actions: read
    steps:
      - run: printenv
      - if: ${{ matrix.runner == 'ubuntu-slim' }}
        run: ls -la /.dockerenv || true
      - if: ${{ matrix.runner == 'ubuntu-slim' }}
        run: cat /proc/1/cgroup || true
  experiment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: $/actions/instrument/job
        with:
          # secrets_to_redact: '{"foo":"*"}'
          secrets_to_redact: '${{ toJSON(secrets) }}'
          debug: 1
        env:
          OTEL_SHELL_CONFIG_GITHUB_INJECT_ON_MAIN: 'TRUE'
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
          OTEL_SHELL_SDK_OUTPUT_REDIRECT: /dev/stderr
      - uses: renovatebot/github-action@37beffda261423addd537c33f2d126df7f6ffbab # v46.2.6
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_DRY_RUN: full
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
